name: publish
on:
  workflow_dispatch:
  push:
    tags:
      - '**'

env:
  MODRINTH_ID: Ohbdou19
  CURSEFORGE_ID: 1251738

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: build
        run: ./gradlew clean build

      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ReplaceBlocksModArtifacts
          path: jars/

      - name: get changelog
        id: changelog
        run: |
          # Get the latest changelog from CHANGELOG.md
          {
            echo "changelog<<EOF"
            awk 'p && /^#/ { exit } p && NF { print } /^#/ { p=1 }' CHANGELOG.md
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: publish 1.20.x
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ReplaceBlocksMod ${{ github.ref_name }} for Minecraft 1.20.x
          changelog: ${{ steps.changelog.outputs.changelog }}
          files: |
            jars/*-1.20.x-!(*-sources).jar
          game-versions: |
            >=1.20 <1.21
          java: |
            17
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          fail-mode: warn

      - name: publish 1.21.x
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          name: ReplaceBlocksMod ${{ github.ref_name }} for Minecraft 1.21.x
          changelog: ${{ steps.changelog.outputs.changelog }}
          files: |
            jars/*-1.21.x-!(*-sources).jar
          game-versions: |
            >=1.21 <1.22
          java: |
            21
          modrinth-id: ${{ env.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ env.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          fail-mode: warn
